// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCduF8ap0LLnCpeco0sklESohJA9nU4zB4',
    appId: '1:237175536095:web:a5f05fa56749015b65ac6a',
    messagingSenderId: '237175536095',
    projectId: 'hodor-e2e1f',
    authDomain: 'hodor-e2e1f.firebaseapp.com',
    storageBucket: 'hodor-e2e1f.appspot.com',
    measurementId: 'G-C16CHVTDES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu8-Jo0GfQu_pAsK5Qa3ZWt5Vb8GzY1qc',
    appId: '1:237175536095:android:2e8b4e7eb5e58b7265ac6a',
    messagingSenderId: '237175536095',
    projectId: 'hodor-e2e1f',
    storageBucket: 'hodor-e2e1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrQAEpzjf_YPvKx19BsFzM8laluwmNaNw',
    appId: '1:237175536095:ios:14b70375244febd865ac6a',
    messagingSenderId: '237175536095',
    projectId: 'hodor-e2e1f',
    storageBucket: 'hodor-e2e1f.appspot.com',
    iosBundleId: 'com.teacharabia.hodor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrQAEpzjf_YPvKx19BsFzM8laluwmNaNw',
    appId: '1:237175536095:ios:4012be1c9d7407ee65ac6a',
    messagingSenderId: '237175536095',
    projectId: 'hodor-e2e1f',
    storageBucket: 'hodor-e2e1f.appspot.com',
    iosBundleId: 'com.example.hodor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCduF8ap0LLnCpeco0sklESohJA9nU4zB4',
    appId: '1:237175536095:web:4e61d3e93e713c8065ac6a',
    messagingSenderId: '237175536095',
    projectId: 'hodor-e2e1f',
    authDomain: 'hodor-e2e1f.firebaseapp.com',
    storageBucket: 'hodor-e2e1f.appspot.com',
    measurementId: 'G-P7JFSDPE5Z',
  );
}
